### ISSUE TITLE
Citing Thermobench

### ISSUE THREAD

**Issue by benedond** [CTU-IIG/thermobench#36]
Add `Cite as` section into readme referring to _Testbed for thermal and performance analysis in MPSoC systems_ paper.

**Comment by wentasah** [comment]
Can you prepare a pull request? You can do it here: https://github.com/CTU-IIG/thermobench/edit/master/README.md

**Comment by benedond** [comment]
I have prepared the pull request. Feel free to modify it according to your preferences.
