### ISSUE TITLE
TB_OPTS log work_done every x seconds

### ISSUE THREAD

**Issue by benedond** [CTU-IIG/thermobench#42]
TB_OPTS allow one to log work_done_every x iterations. However, there is large difference between the execution times of a single iteration across various benchmarks. It is hard to tune after how many iterations to make a log to obtain a sensible .csv output file.

It might be practical to allow user log work_done every x seconds instead. But I am not sure, whether it would not negatively affect julia processing functions.

**Comment by wentasah** [comment]
It should not affect Julia. I'm adding there `--work_done_every_sec`.

**Comment by benedond** [comment]
Thank you.
