### ISSUE TITLE
Data types in julia ops_est function - information loss

### ISSUE THREAD

**Issue by benedond** [CTU-IIG/thermobench#43]
Some benchmarks are executed rather fast and so numbers in `_work_done` columns can be quite large. Then ops_est function seems to loose precision when handling these values. E.g., having a column like

```
 res.df.CPU4_work_done
2878-element Array{Union{Missing, Float64},1}:
       missing
      0.0
 131172.20808998644
     ...
      1.841302418e9
      1.84232735e9
       missing
```

and calling `Thermobench.ops_est(df)` results in `Inf ± NaN`.

[prime-A72-1.yaml.zip](https://github.com/CTU-IIG/thermobench/files/5781564/prime-A72-1.yaml.zip)

**Comment by wentasah** [comment]
The problem is in the data:
```
julia> d = T.read("prime-A72-1.yaml.csv");
julia> d.df[895:897, [:time, :CPU4_work_done]]
3×2 DataFrame
 Row │ time     CPU4_work_done 
     │ Float64  Float64?       
─────┼─────────────────────────
   1 │ 280.228       5.71435e8
   2 │ 280.228       5.72461e8
   3 │ 280.228       5.73485e8
```
As you can see, there are three different "work_done" values in the same time instant. This can happen when thermobench is not scheduled fast enough to read all distinct lines from the benchmark.

We can probably add some option to drop these data points automatically.
